# -*- coding: utf-8 -*-
"""political-polarization-us-congress.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q10Bj5AEbtYE5K0U7vYVAQe7wK85jZha

## Creating Visualizations

### Loading and Installing Dependencies
"""

library(pacman)

p_load(tidyverse, ggplot2, ggrepel)

"""### Loading the Current Nominate Data from Voteview.com"""

nom_dat <- read_csv("https://voteview.com/static/data/out/members/HSall_members.csv")

"""### Transforming the Member-Year NOMINATE Data into the Chamber-Year Data on Polarization"""

south <- c(40:49,51,53)
polar_dat <- nom_dat %>%
    filter(congress>45 &
           chamber != "President") %>%
    mutate(
      year = 2*(congress-1) + 1789,
    ) %>%
    group_by(chamber,congress,year) %>%
    summarize(
      party.mean.diff.d1 = mean(nominate_dim1[party_code==200],na.rm=T) -
                           mean(nominate_dim1[party_code==100],na.rm=T),
      prop.moderate.d1 = mean(abs(nominate_dim1)<0.25,na.rm=T),
      prop.moderate.dem.d1 = mean(abs(nominate_dim1[party_code==100])<0.25,na.rm=T),
      prop.moderate.rep.d1 = mean(abs(nominate_dim1[party_code==200])<0.25,na.rm=T),
      overlap = (sum(nominate_dim1[party_code==200] <
                       max(nominate_dim1[party_code==100],na.rm=T),na.rm=T)  +
                 sum(nominate_dim1[party_code==100] >
                       min(nominate_dim1[party_code==200],na.rm=T),na.rm=T))/
                 (sum(!is.na(nominate_dim1[party_code==100]))+
                  sum(!is.na(nominate_dim1[party_code==200]))),
      chamber.mean.d1 = mean(nominate_dim1,na.rm=T),
      chamber.mean.d2 = mean(nominate_dim2,na.rm=T),
      dem.mean.d1 = mean(nominate_dim1[party_code==100],na.rm=T),
      dem.mean.d2 = mean(nominate_dim2[party_code==100],na.rm=T),
      rep.mean.d1 = mean(nominate_dim1[party_code==200],na.rm=T),
      rep.mean.d2 = mean(nominate_dim2[party_code==200],na.rm=T),
      north.rep.mean.d1 = mean(nominate_dim1[party_code==200 &
                                             !(state_icpsr %in% south)],na.rm=T),
      north.rep.mean.d2 = mean(nominate_dim2[party_code==200 &
                                             !(state_icpsr %in% south)],na.rm=T),
      south.rep.mean.d1 = mean(nominate_dim1[party_code==200 &
                                              (state_icpsr %in% south)],na.rm=T),
      south.rep.mean.d2 = mean(nominate_dim2[party_code==200 &
                                             (state_icpsr %in% south)],na.rm=T),
      north.dem.mean.d1 = mean(nominate_dim1[party_code==100 &
                                              !(state_icpsr %in% south)],na.rm=T),
      north.dem.mean.d2 = mean(nominate_dim2[party_code==100 &
                                              !(state_icpsr %in% south)],na.rm=T),
      south.dem.mean.d1 = mean(nominate_dim1[party_code==100 &
                                              (state_icpsr %in% south)],na.rm=T),
      south.dem.mean.d2 = mean(nominate_dim2[party_code==100 &
                                              (state_icpsr %in% south)],na.rm=T),
    )

"""### Preview of Resulting Dataset"""

head(polar_dat)
write_csv(polar_dat,path="Political Polarization in US Congress (Non-Assorted).csv")
# IMPORTANT: Make sure to download the non-assorted file first!

"""### Party Means on the Liberal-Conservative Dimension Over Time By Chamber"""

polar_dat_long <- polar_dat %>% gather(score,value,-chamber,-year,-congress)
labels <- c("dem.mean.d1"="DEM",
            "rep.mean.d1"="REP",
            "north.dem.mean.d1"="N. DEM",
            "south.dem.mean.d1"="S. DEM")

polarized_plot <- function(chamb) {
  pdatl <- polar_dat_long %>%
                filter(chamber==chamb,
                       score %in% c("dem.mean.d1","rep.mean.d1",
                                    "north.dem.mean.d1","south.dem.mean.d1")) %>%
                mutate(party=labels[score]) %>%
                ungroup()

  gg <- ggplot(data=pdatl,
               aes(x=year,y=value,group=party,col=party)) +
               scale_x_continuous(expand = c(0.15, 0),
                                 breaks=seq(1880, max(pdatl$year), by=8)) +
               geom_line() + geom_point(size=0.7) +
               xlab("Year") + ylab("Liberal-Conservative") +
               geom_text_repel(data=pdatl %>%
                    filter(year == min(year)),
                  aes(label = party, color = party),
                  size = 3,
                  nudge_x = -8,
                  point.padding = 0.1,
                  segment.color = NA,
                  show.legend = FALSE) +
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
              scale_color_manual(values=c("REP"="#c70828","DEM"="#1372ad",
                                         "N. DEM"="#6194F4",
                                         "S. DEM"="#81c4e4"),guide="none") +
              theme_bw()
  gg
}

"""## House"""

gg <- polarized_plot("House")
ggsave("voteview_house_party_means.png", plot=gg, device="png",
       width=25, height=14, dpi=600)
gg + ggtitle("House") + theme(plot.title = element_text(hjust = 0.5))

"""## Senate"""

gg <- polarized_plot("Senate")
ggsave("voteview_senate_party_means.png", plot=gg, device="png",
       width=25, height=14, dpi=300)
gg + ggtitle("Senate") + theme(plot.title = element_text(hjust = 0.5))

"""## Liberal-Conservative Partisan Polarization By Chamber"""

gg <- ggplot(polar_dat_long %>%
              filter(score == "party.mean.diff.d1"),
              aes(x=year,y=value,group=chamber,col=chamber)) +
              scale_x_continuous(expand = c(0.10, 0), breaks=seq(1880,max(polar_dat_long$year),by=8)) +
              geom_line() + geom_point(size=0.7) +
              xlab("Year") + ylab("Distance between party means") +
              geom_text_repel(data=polar_dat_long %>%
                    ungroup() %>%
                    filter(year == min(year) & score=="party.mean.diff.d1"),
                  aes(label = chamber, color = chamber),
                  size = 3,
                  nudge_x = -10,
                  point.padding = 0.1,
                  segment.color = NA,
                  show.legend = FALSE) +
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
              scale_color_manual(values=c("House"="#c70828","Senate"="#1372ad"),guide="none") +
              theme_bw()

ggsave("voteview_party_mean_diff.png", plot=gg, device="png",
       width=25, height=14, dpi=300)
gg + ggtitle("Liberal-Conservative Partisan Polarization By Chamber") + theme(plot.title = element_text(hjust = 0.5))